#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const c = require("./protocol.js");

const out = path.join(__dirname, "..", "editor-extension", "lib", "contract.js");
const body = `"use strict";

// Generated by contract/sync.js. Do not edit.
// The extension is packaged as a .vsix and cannot require outside its own
// directory, so the shared contract is copied here and drift-checked in CI.

module.exports = ${JSON.stringify(
  { PROTOCOL_VERSION: c.PROTOCOL_VERSION, ERROR_CODES: c.ERROR_CODES, SIDES: c.SIDES, MODES: c.MODES, STOP_TYPES: c.STOP_TYPES },
  null,
  2
)};
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`wrote ${out}`);
